<br/>
<div id="buckets">
	<div class="grid2col">
		<div class="register"><h2>Update User Password</h2>
			<br/>
			<p>
		
			<form method="post" action="/user/password">
	<div class="row">
		<div class="label">First Name</div>
		<div>
			<?php echo $this->user->first_name;?>			
		</div>
	</div>
	
	<div class="row">
		<div class="label">Last Name</div>
		<div style="float:left">
			<?php echo $this->user->last_name;?>			
		</div>
	</div>
	
	<div class="row">
		<div class="label">Email</div>
		<div style="float:left">
			<?php echo $this->user->email;?>			
		</div>
	</div>
	
	<div class="row">
		<div class="label">Password</div>
		<div style="float:left">
			<input type="text" name="password" id="password"/>			
		</div>
	</div>
	
	<div class="row">
		<div class="label">
		<input type="hidden" name="user_id" value="<?php echo $this->user->user_id;?>"/>
			<input type="submit" value=" Update Password "/>
		</div>
	</div>
	
</form>
			</p>
		</div>				
	</div>			
</div><!--/buckets-->

