<?php $this->headTitle('Current Students enrolled'); ?>
<div id="page_content">
	<div id="content"><br/>
	<a href="/admin/index/" style="font-size:15px;">Admin Menu</a>
	<br/>
	<br/>
			<table style="border:2px solid gray;width:895px;color:black;font-weight:bold;table-layout:fixed;
	cell-padding:15px;">
	<tr>
		<td width="120px">Students Enrolled</td>
		<td width="290px" style="text-align: center;">Email</td>
		<td width="200px" style="text-align: center;">Referrer</td>
	</tr>
	</table>

			
			<?php 
				foreach($this->students as $student)
				{
					
			?>
			<table style="border:2px solid gray;width:895px;color:gray;cell-padding:15px;table-layout:fixed;">
			<tr>
			<td style="width:250px;"><?php  echo $student->first_name;?> <?php 
			echo $student->last_name;
			?>
			</td>
			
			<td  style="width:300px;">
				<a href="/admin/enrolled-courses/email/<?php echo $student->email?>/">
					<?php 
						 echo $student->email;
						 ?>
				</a>
				</td>
			<td style="overflow: hidden; width: 200px;whitespace: nowrap;text-overflow: ellipsis;">
					<?php 
						 echo $student->referrer;
						 ?>
				
				</td>	
				
				</tr>
				</table>
			<?php 	
				}
			?>
			
</div></div>