<?php $this->headTitle('Display batches'); ?>
<div id="page_content">
	<div id="content">



<div>
	<br/>
	<a href="/admin/index/" style="font-size:15px;">Admin Menu</a>
	<br/>
	<br/>
 <table style="font-size:30px;color:gray;width:800px;"><tr><td style="width:600px">Class Schedule</td>
			</tr></table><br/>
 <table style="border:2px solid gray;padding:15px;width:800px;font-weight:bold;">
	<tr>
		<td width="50px"></td>
		<td width="200px">Start Date</td>
		<td width="200px">Class Days</td>
		<td width="300px">Class Time</td>
		
	</tr>
</table>

 <?php 
	foreach($this->batches as $batch)
	{
?>
	<table style="border:2px solid gray;width:800px;color:gray;
	cell-padding:15px;">
	
	<div style="font-size: 25px;">
	<tr style="border:2px solid gray">
	<td width="50px"></td>
	<td width="200px">
		<a href="/admin/display-topic/course_id/<?php echo $batch->course_id?>
		/batch_id/<?php echo $batch->batch_id?>/">
		<?php echo $batch->starting_date;?></a>
		</td>
	<td  style="width:200px;">
		<?php echo $batch->class_days;?>
		</td>
	<td width="300px">
		<?php echo $batch->class_time;?>
		</td>
	</tr>
		
	</div>
	</table>
	
	
	<?php 
		
		
	}
?>

	
</div></div></div>