<br/>
<div id="buckets">
	<div class="grid2col">
	<div id="page_content">
		<div id="content">
		<div class="box">
			<div class="box_content">
		
		
		<section class="login"><h2 style="color:gray;font-size:25px;">Admin Menu</h2>
			<br/>
			<p>
			<b>Faculty</b>
			<br/><br/>
			<a href="/admin/add-faculty">Add new Faculty</a>
			<br/><br/>
			<a href="/user/list-faculty">View Faculty</a>
			<br/><br/>
			<b>Course</b>
			<br/><br/>
			<a href="/admin/add-course">Add New Course</a>
			<br/><br/>
			<a href="/course/list-courses">List Courses</a>
			<br/><br/>
			<a href="/admin/upload-course">Upload Video</a>
			<br/></br>
			<a href="/admin/show-course">Insert Video</a>
			<br/></br>
			<b>Students</b>
			<br/><br/>
			<a href="/admin/view-courses">View Enrolled Courses by Student</a>
			<br/></br>
			<a href="/admin/display-course">View Students in a Batch</a>
			<br/></br>
			<a href="/admin/discount-code">Create Discount Code</a>
			<br/></br>
			<a href="/admin/get-courses">Update Discount Code</a>
			<br/>
			</p>
			<br/>
			<h3 style="color:gray;font-size:20px;">Quiz</h3>
			<br/>
			<a href="/quiz/add-quiz">Create Quiz</a>
			<br/></br>
			<a href="/quiz/list-quizzes">List Quizzes</a></br>
		</section>				
	</div>			
</div>
</div></div></div></div>

<!--/buckets-->