<?php $this->headTitle('Get your enrolled Courses'); ?>
<div id="page_content">
	<div id="content">
		<div class="box">
			<div class="box_content">
			<a href="/admin/index/" style="font-size:15px;">Admin Menu</a>
			<br/>
			<br/>
	<form method="post" action="/admin/enrolled-courses">
	<p style="font-size:30;color:orange;">Enter your email id:
		<input type="email" name="email" placeholder="Email id" />
		</p>
		<br/>
	<p><input type="submit" value="submit">
		</p>
</form>
</div></div></div></div>